package uy.edu.ude.BuscadorProyectos.ui.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ProyectoViewDesign extends VerticalLayout {
	protected HorizontalLayout cabezalProyecto;
	protected Label orderId;
	protected Label stateLabel;
	protected Label headerNombreProyecto;
	protected TextField txtNombreProyecto;
	protected Label headerCarrera;
	protected TextField txtCarrera;
	protected HorizontalLayout contenedorAnioNota;
	protected Label headerAnio;
	protected TextField txtAnio;
	protected Label headerNota;
	protected TextField txtNota;
	protected Label headerResumen;
	protected TextArea txtResumen;
	protected HorizontalLayout contenedorTutorAlumnos;
	protected Label headerTutor;
	protected TextField txtTutor;
	protected Label headerAlumnos;
	protected TextArea txtAlumnos;
	protected Label headerTecnologia;
	protected Grid<uy.edu.ude.BuscadorProyectos.valueObjects.TecnologiaVO> grdTecnologias;
	protected Label headerModeloProceso;
	protected Grid<uy.edu.ude.BuscadorProyectos.valueObjects.TecnologiaVO> grdModeloProceso;
	protected Label headerMetodologiaTesting;
	protected Grid<uy.edu.ude.BuscadorProyectos.valueObjects.TecnologiaVO> grdMetodologiaTesting;

	public ProyectoViewDesign() {
		Design.read(this);
	}
}
