package uy.edu.ude.BuscadorProyectos.ui.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Upload;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ProyectosUploadViewDesign extends VerticalLayout {
	protected TextField search;
	protected Button add;
	protected Grid<uy.edu.ude.BuscadorProyectos.entity.Proyecto> list;
	protected VerticalLayout form;
	protected TextField nombre;
	protected TextField anio;
	protected TextField carrera;
	protected TextField nota;
	protected Upload updProyecto;
	protected Button update;
	protected Button cancel;
	protected Button delete;

	public ProyectosUploadViewDesign() {
		Design.read(this);
	}
}
