package uy.edu.ude.BuscadorProyectos.ui.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Grid;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TecnologiasViewDesign extends VerticalLayout {
	protected TextField search;
	protected Button addCategoria;
	protected Button addTecnologia;
	protected Grid<uy.edu.ude.BuscadorProyectos.entity.Categoria> gridcategoria;
	protected Grid<uy.edu.ude.BuscadorProyectos.entity.Tecnologia> gridtecnologia;
	protected VerticalLayout form;
	protected ComboBox<uy.edu.ude.BuscadorProyectos.entity.Categoria> cmbCategoria;
	protected TextField txtCategoria;
	protected TextField tecnologia;
	protected Button update;
	protected Button cancel;
	protected Button delete;

	public TecnologiasViewDesign() {
		Design.read(this);
	}
}
