package uy.edu.ude.BuscadorProyectos.ui.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Grid;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UsuariosViewDesign extends VerticalLayout {
	protected TextField search;
	protected Button btnNuevo;
	protected Grid<uy.edu.ude.BuscadorProyectos.ValueObjects.UsuarioVO> grdUsuarios;
	protected VerticalLayout form;
	protected TextField usuario;
	protected PasswordField contrasenia;
	protected PasswordField contrasenia2;
	protected TextField nombre;
	protected TextField apellido;
	protected TextField email;
	protected ComboBox<uy.edu.ude.BuscadorProyectos.ValueObjects.PerfilVO> cmbPerfil;
	protected Button btnAgregar;
	protected Button btnModificar;
	protected Button btnCancelar;
	protected Button btnBorrar;

	public UsuariosViewDesign() {
		Design.read(this);
	}
}
